### ISSUE TITLE
Brak możliwości usunięcia przedmiotu ze sklepu

### ISSUE THREAD

**Issue by opiepl** [Adexion/GameSitesIssue#1]
Wczoraj dodałem VIPa w sklepie, ale po aktualizacji nie mogę go usunąć.
Sklep: sfite.gamesites.pl
![image](https://user-images.githubusercontent.com/75224417/144754192-15335b61-d95c-43b8-8ac6-fd5f510fcb09.png)

**Comment by opiepl** [comment]
https://sfite.gamesites.pl/pl/shop/1

**Comment by Adexion** [comment]
2 możliwości:

1. usunięcie nie używanego przedmiotu i podmiana już tego użytego w voucherze 
2. usunięcie historii dotyczącej płatności  dla przedmiotu, a następnie usunięcie przedmiotu
