### ISSUE TITLE
błąd error strony

### ISSUE THREAD

**Issue by likasop** [Adexion/GameSitesIssue#5]
Podczas edytowania opisu rangi i zapisania wyskakuje błąd 
![image](https://user-images.githubusercontent.com/94260439/144754610-1144fa02-febf-48b3-bb77-52cf02773168.png)

**Comment by Adexion** [comment]
Poproszę o screen całego uzupełnionego formularza, będzie on wymagany w celu odtworzenia błędu

**Comment by Adexion** [comment]
problem rozwiązany po rozmowie na DC
