### ISSUE TITLE
prośba o dodanie linku do adminstracji

### ISSUE THREAD

**Issue by likasop** [Adexion/GameSitesIssue#6]
![image](https://user-images.githubusercontent.com/94260439/144757023-c291e1d7-6d95-465a-9a1b-cb23aa7b81d1.png)

o tutaj w tym miejscu żeby było <3

**Comment by opiepl** [comment]
Cześć, niestety nie zamierzamy dodać takiego przycisku. Według nas jest niepotrzebny i zaśmieca navbar.

Pozdrawiam,
Michał Dyrka
